const defaultBGColor = "rgba(235,135,69, .3)";
const defaultColor = "#eb7d45";
export const Labels = {
  1: {
    1: {
      top: "47%",
      left: "16.5%",
      width: "43%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: -80,
    },
    2: {
      paddingRight: "10%",
      top: "30%",
      left: "32%",
      width: "28%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: -83,
    },
    3: {
      top: "62%",
      left: "12%",
      width: "30%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: -76,
    },
    4: {
      paddingRight: "5%",
      top: "31%",
      left: "36%",
      width: "28%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: -86,
    },
    5: {
      paddingLeft: "30%",
      top: "18.5%",
      left: "20%",
      width: "50%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: -2,
    },
    6: {
      top: "34%",
      left: "13%",
      width: "20%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: -77,
    },
    7: {
      top: "62%",
      left: "16.5%",
      width: "30%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: -77,
    },
    8: {
      paddingLeft: "5%",
      top: "49%",
      left: "50%",
      width: "20%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: 0,
    },
    9: {
      paddingLeft: "5%",
      top: "60%",
      left: "9%",
      width: "30%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: -76,
    },
  },
  2: {
    1: {
      top: "22%",
      left: "47%",
      width: "20%",
      fontSize: "1.4vw",
      deg: -55,
    },
    2: {
      top: "41.5%",
      left: "38%",
      width: "20%",
      fontSize: "1.4vw",
      deg: -3,
    },
    3: {
      top: "20%",
      left: "53.5%",
      width: "20%",
      fontSize: "1.4vw",
      deg: -55,
    },
    4: {
      top: "32%",
      left: "29%",
      width: "20%",
      fontSize: "1.4vw",
      deg: -87,
    },
    6: {
      top: "54%",
      left: "35%",
      width: "20%",
      fontSize: "1.4vw",
      deg: -2,
    },
    7: {
      top: "13%",
      left: "30%",
      width: "20%",
      fontSize: "1.4vw",
      deg: 1,
    },
    8: {
      top: "46%",
      left: "60%",
      width: "20%",
      fontSize: "1.4vw",
      deg: 30,
    },
    9: {
      top: "26%",
      left: "55%",
      width: "20%",
      fontSize: "1.4vw",
      deg: -58,
    },
    10: {
      top: "15%",
      left: "64%",
      width: "25%",
      fontSize: "1.4vw",
      deg: 24,
    },
    11: {
      top: "24%",
      left: "63%",
      width: "25%",
      fontSize: "1.4vw",
      deg: 25,
    },
    12: {
      top: "77%",
      left: "40%",
      width: "25%",
      fontSize: "1.4vw",
      deg: 5,
    },
  },
  3: {
    1: {
      top: "55%",
      left: "41%",
      width: "15%",
      fontSize: "1.4vw",
    },
    2: {
      top: "68%",
      left: "43%",
      width: "15%",
      fontSize: "1.4vw",
    },
    3: {
      top: "44%",
      left: "43%",
      width: "15%",
      fontSize: "1.4vw",
    },
    4: {
      top: "50%",
      left: "18%",
      width: "15%",
      fontSize: "1.4vw",
      deg: -79,
    },
    5: {
      top: "20%",
      left: "33%",
      width: "15%",
      fontSize: "1.4vw",
      deg: -84,
    },
    6: {
      top: "59%",
      left: "29%",
      width: "15%",
      fontSize: "1.4vw",
      deg: -84,
    },
    7: {
      top: "23%",
      left: "37.5%",
      width: "15%",
      fontSize: "1.4vw",
      deg: -87,
    },
    8: {
      top: "25%",
      left: "11%",
      width: "25%",
      fontSize: "1.4vw",
      deg: -76,
    },
    9: {
      top: "20%",
      left: "42%",
      width: "25%",
      fontSize: "1.4vw",
      deg: -91,
    },
    10: {
      top: "31%",
      left: "25%",
      width: "25%",
      fontSize: "1.4vw",
      deg: 1,
    },
    11: {
      top: "78%",
      left: "0.3%",
      width: "25%",
      fontSize: "1.4vw",
      deg: -73,
    },
    12: {
      top: "15%",
      left: "23%",
      width: "25%",
      fontSize: "1.4vw",
      deg: -82,
    },
    13: {
      top: "5%",
      left: "35%",
      width: "25%",
      fontSize: "1.4vw",
      deg: -2,
    },
    14: {
      top: "5%",
      left: "5%",
      width: "25%",
      fontSize: "1.4vw",
      deg: -2,
    },
  },
  4: {
    1: {
      paddingRight: "5%",
      top: "45%",
      left: "30%",
      width: "60%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: -3,
    },
    2: {
      paddingRight: "5%",
      top: "53%",
      left: "26%",
      width: "64%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: -3,
    },
    4: {
      paddingRight: "20%",
      top: "48%",
      left: "43%",
      width: "43%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: -102,
    },
    5: {
      paddingRight: "8%",
      top: "3%",
      left: "26%",
      width: "64%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: -3,
    },
    6: {
      // paddingRight: "8%",
      top: "62%",
      left: "26%",
      width: "64%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: -3,
    },
    7: {
      paddingRight: "13%",
      top: "66%",
      left: "25.7%",
      width: "26%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: -87,
    },
    8: {
      top: "30%",
      left: "48.7%",
      width: "15%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: -3,
    },
  },
  5: {
    1: {
      top: "31.5%",
      left: "29%",
      width: "13%",
      fontSize: "1.4vw",
      background: `${defaultBGColor}`,
      padding: "9% 4% 9% 4%",
      borderRadius: "5%",
      deg: 9,
    },
    2: {
      top: "50%",
      left: "40.3%",
      width: "20%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: -91,
    },
    3: {
      top: "19.5%",
      left: "40.3%",
      width: "20%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: -1.5,
    },
    4: {
      top: "8%",
      left: "64%",
      width: "15%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: -1.5,
    },
    5: {
      top: "19.5%",
      left: "70.5%",
      width: "20%",
      fontSize: "1.4vw",
      paddingLeft: "4%",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: 66.5,
    },
    7: {
      top: "8%",
      left: "32%",
      width: "8%",
      fontSize: "1.4vw",
      padding: "1%",
      background: `${defaultBGColor}`,
      borderRadius: "50%",
    },
    9: {
      top: "11%",
      left: "22%",
      width: "7%",
      fontSize: "1.4vw",
      background: `${defaultBGColor}`,
      padding: "1%",
      borderRadius: "50%",
    },
    11: {
      top: "38%",
      left: "51%",
      width: "40%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: -1,
    },
  },
  6: {
    1: {
      top: "48%",
      left: "1%",
      width: "95%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: -2.5,
    },
    2: {
      top: "35.8%",
      left: "20%",
      width: "60%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: -2.4,
    },
    3: {
      top: "22%",
      left: "38%",
      width: "50%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      paddingRight: "25%",
      deg: -2.4,
    },
    4: {
      top: "11%",
      left: "1%",
      width: "83%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: -1.6,
    },
    5: {
      top: "62%",
      left: "1%",
      width: "80%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: -2.5,
    },
    6: {
      top: "28.6%",
      left: "38%",
      width: "37%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      paddingRight: "15%",
      deg: -2.4,
    },
    7: {
      top: "44.6%",
      left: "46.5%",
      width: "40%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: 76,
    },
    8: {
      top: "86%",
      left: "35.5%",
      width: "40%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: -3.5,
    },
    9: {
      top: "44.6%",
      left: "41%",
      width: "40%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: 78.5,
    },
    10: {
      top: "68.5%",
      left: "35.5%",
      width: "40%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: -3,
    },
  },
  7: {
    1: {
      top: "42%",
      left: "22%",
      width: "68%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: -1,
      paddingLeft: "18%",
    },
    2: {
      top: "27%",
      left: "47%",
      width: "50%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: -1,
      paddingRight: "16%",
    },
    3: {
      top: "56.5%",
      left: "1%",
      width: "95%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: -1,
      paddingLeft: "37%",
    },
    4: {
      top: "46.5%",
      left: "23.8%",
      width: "41%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: 90,
      paddingLeft: "23%",
    },
    5: {
      top: "46.5%",
      left: "35.5%",
      width: "41%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: 85.7,
      paddingLeft: "23%",
    },
    7: {
      top: "0%",
      left: "44.5%",
      width: "41%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: 0,
      paddingRight: "3%",
    },
    9: {
      top: "22.5%",
      left: "60.5%",
      width: "20%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: 79.3,
      paddingRight: "5%",
    },
    10: {
      top: "20%",
      left: "50%",
      width: "38%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      paddingRight: "14%",
    },
  },
  8: {
    1: {
      top: "22%",
      left: "47%",
      width: "20%",
      fontSize: "1.4vw",
    },
  },
  9: {
    1: {
      top: "55.5%",
      left: "44%",
      width: "28%",
      fontSize: "1.4vw",
      background: `${defaultBGColor}`,
      padding: "4% 6% 4% 6%",
      borderRadius: "50%",
      deg: 0,
    },
    2: {
      top: "31%",
      left: "45%",
      width: "24%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: 2,
    },
    3: {
      top: "55.5%",
      left: "25%",
      width: "15%",
      fontSize: "1.4vw",
      background: `${defaultBGColor}`,
      padding: "3% 3% 3% 3%",
      borderRadius: "50%",
      deg: 0,
    },
    4: {
      top: "84.5%",
      left: "44%",
      width: "28%",
      fontSize: "1.4vw",
      background: `${defaultBGColor}`,
      padding: "2% 1% 2% 1%",
      borderRadius: "50%",
      deg: 0,
    },
    5: {
      top: "48%",
      left: "23%",
      width: "38%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: -80,
    },
  },
  10: {
    1: {
      top: "22%",
      left: "47%",
      width: "20%",
      fontSize: "1.4vw",
    },
  },
  11: {
    1: {
      top: "22%",
      left: "47%",
      width: "20%",
      fontSize: "1.4vw",
    },
  },
  12: {
    1: {
      top: "22%",
      left: "47%",
      width: "20%",
      fontSize: "1.4vw",
    },
  },
  13: {
    1: {
      top: "22%",
      left: "47%",
      width: "20%",
      fontSize: "1.4vw",
    },
  },
  14: {
    1: {
      top: "43.5%",
      left: "30%",
      width: "24%",
      fontSize: "1.5vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: 17,
    },
    2: {
      top: "24.5%",
      left: "36%",
      width: "12%",
      fontSize: "1.5vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: -71,
      paddingLeft: "3%",
    },
    4: {
      top: "33.5%",
      left: "6%",
      width: "24%",
      fontSize: "1.5vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: 6,
    },
    6: {
      top: "18.5%",
      left: "0%",
      width: "12%",
      fontSize: "1.5vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: -42,
      paddingLeft: "3%",
    },
    7: {
      top: "15.5%",
      left: "15%",
      width: "15%",
      fontSize: "1.5vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: 12,
    },
  },
  15: {
    1: {
      top: "73%",
      left: "25%",
      width: "8%",
      fontSize: "2.5vw",
    },
  },
  16: {
    1: {
      top: "73%",
      left: "25%",
      width: "8%",
      fontSize: "2.5vw",
    },
  },
  17: {
    1: {
      top: "73%",
      left: "25%",
      width: "8%",
      fontSize: "2.5vw",
    },
  },
  18: {
    1: {
      top: "73%",
      left: "25%",
      width: "8%",
      fontSize: "2.5vw",
    },
  },
  19: {
    1: {
      top: "73%",
      left: "25%",
      width: "8%",
      fontSize: "2.5vw",
    },
  },
  20: {
    1: {
      top: "22%",
      left: "47%",
      width: "20%",
      fontSize: "1.4vw",
    },
  },
  21: {
    1: {
      top: "22%",
      left: "47%",
      width: "20%",
      fontSize: "1.4vw",
    },
  },
  22: {
    1: {
      top: "22%",
      left: "47%",
      width: "20%",
      fontSize: "1.4vw",
    },
  },
  23: {
    1: {
      top: "22%",
      left: "47%",
      width: "20%",
      fontSize: "1.4vw",
    },
  },
  24: {
    1: {
      top: "73%",
      left: "25%",
      width: "8%",
      fontSize: "2.5vw",
    },
  },
  25: {
    1: {
      top: "22%",
      left: "47%",
      width: "20%",
      fontSize: "1.4vw",
    },
  },
  26: {
    1: {
      top: "22%",
      left: "47%",
      width: "20%",
      fontSize: "1.4vw",
    },
  },
  27: {
    1: {
      top: "73%",
      left: "25%",
      width: "8%",
      fontSize: "2.5vw",
    },
  },
  28: {
    1: {
      top: "73%",
      left: "25%",
      width: "8%",
      fontSize: "2.5vw",
    },
  },
  29: {
    1: {
      top: "73%",
      left: "25%",
      width: "8%",
      fontSize: "2.5vw",
    },
  },
  30: {
    1: {
      top: "22%",
      left: "47%",
      width: "20%",
      fontSize: "1.4vw",
    },
  },
  31: {
    1: {
      top: "22%",
      left: "47%",
      width: "20%",
      fontSize: "1.4vw",
    },
  },
  32: {
    1: {
      top: "22%",
      left: "47%",
      width: "20%",
      fontSize: "1.4vw",
    },
  },
  33: {
    1: {
      top: "22%",
      left: "47%",
      width: "20%",
      fontSize: "1.4vw",
    },
  },
  34: {
    1: {
      top: "73%",
      left: "25%",
      width: "8%",
      fontSize: "2.5vw",
    },
  },
  35: {
    1: {
      top: "22%",
      left: "47%",
      width: "20%",
      fontSize: "1.4vw",
    },
  },
  36: {
    1: {
      top: "22%",
      left: "47%",
      width: "20%",
      fontSize: "1.4vw",
    },
  },
  37: {
    1: {
      top: "73%",
      left: "25%",
      width: "8%",
      fontSize: "2.5vw",
    },
  },
  38: {
    1: {
      top: "22%",
      left: "47%",
      width: "20%",
      fontSize: "1.4vw",
    },
  },
  39: {
    1: {
      top: "22%",
      left: "47%",
      width: "20%",
      fontSize: "1.4vw",
    },
  },
  40: {
    1: {
      top: "73%",
      left: "25%",
      width: "8%",
      fontSize: "2.5vw",
    },
  },
  41: {
    1: {
      top: "73%",
      left: "25%",
      width: "8%",
      fontSize: "2.5vw",
    },
    2: {
      top: "65%",
      left: "47%",
      width: "10%",
      fontSize: "2.5vw",
    },
    3: {
      top: "29%",
      left: "59%",
      width: "12%",
      fontSize: "2.5vw",
    },
    4: {
      top: "28%",
      left: "50%",
      width: "8%",
      fontSize: "2.5vw",
    },
    5: {
      top: "31%",
      left: "30%",
      width: "8%",
      fontSize: "2.5vw",
    },
    7: {
      top: "9%",
      left: "65%",
      width: "12%",
      deg: "25",
      fontSize: "2.5vw",
    },
    8: {
      top: "29%",
      left: "14%",
      width: "10%",
      fontSize: "2.5vw",
    },
  },
  42: {
    1: {
      top: "22%",
      left: "47%",
      width: "20%",
      fontSize: "1.4vw",
    },
  },
  43: {
    1: {
      top: "73%",
      left: "25%",
      width: "8%",
      fontSize: "2.5vw",
    },
  },
  44: {
    1: {
      padding: "2vw 0",
      top: "60%",
      left: "45%",
      width: "14%",
      fontSize: "2.5vw",
      borderRadius: "50%",
      background: `${defaultBGColor}`,
    },
    2: {
      padding: "3.5vw 0",
      top: "35%",
      left: "23%",
      width: "14%",
      fontSize: "2.5vw",
      borderRadius: "50%",
      background: `${defaultBGColor}`,
    },
    3: {
      padding: "5vw 0",
      top: "35%",
      left: "3%",
      width: "14%",
      fontSize: "2.5vw",
      borderRadius: "50%",
      background: `${defaultBGColor}`,
    },
    4: {
      padding: "2.5vw 0",
      top: "35%",
      left: "65%",
      width: "14%",
      fontSize: "2.5vw",
      borderRadius: "50%",
      background: `${defaultBGColor}`,
    },
    5: {
      padding: "3vw 0",
      top: "2%",
      left: "45%",
      width: "14%",
      fontSize: "2.5vw",
      borderRadius: "50%",
      background: `${defaultBGColor}`,
    },
    6: {
      padding: "3vw 0",
      top: "2%",
      left: "65%",
      width: "14%",
      fontSize: "2.5vw",
      borderRadius: "50%",
      background: `${defaultBGColor}`,
    },
  },
  45: {
    1: {
      top: "47%",
      left: "36.4%",
      width: "44%",
      fontSize: "1.4vw",
      deg: -91,
      borderBottom: `.3vw solid ${defaultColor}`,
    },
  },
  46: {
    1: {
      padding: "4.5vw",
      top: "60%",
      left: "40%",
      width: "15%",
      fontSize: "1.4vw",
      borderRadius: "50%",
      background: `${defaultBGColor}`,
    },
    2: {
      padding: "4.5vw",
      top: "60%",
      left: "22%",
      width: "14%",
      fontSize: "1.4vw",
      borderRadius: "50%",
      background: `${defaultBGColor}`,
    },
    3: {
      top: "15.5%",
      left: "37%",
      width: "30%",
      fontSize: "1.4vw",
      deg: 15,
      borderBottom: `.3vw solid ${defaultColor}`,
    },
    4: {
      top: "18.5%",
      left: "29.5%",
      width: "12%",
      fontSize: "1.4vw",
      deg: -63,
      borderBottom: `.3vw solid ${defaultColor}`,
    },
  },
  47: {
    1: {
      top: "40%",
      left: "30%",
      width: "50%",
      fontSize: "1.4vw",
      deg: -49.5,
      borderBottom: `.3vw solid ${defaultColor}`,
    },
    2: {
      top: "42%",
      left: "60%",
      width: "32%",
      fontSize: "1.4vw",
      deg: 36,
      borderBottom: `.3vw solid ${defaultColor}`,
    },
    3: {
      top: "42%",
      left: "3%",
      width: "60%",
      fontSize: "1.4vw",
      deg: -75,
    },
    4: {
      top: "16%",
      left: "44%",
      width: "10%",
      fontSize: "1.4vw",
      deg: -86,
      borderBottom: `.3vw solid ${defaultColor}`,
    },
    5: {
      top: "13%",
      left: "53%",
      width: "12%",
      fontSize: "1.4vw",
      deg: -80,
      borderBottom: `.3vw solid ${defaultColor}`,
    },
  },
  48: {
    1: {
      top: "22%",
      left: "47%",
      width: "20%",
      fontSize: "1.4vw",
    },
  },
  49: {
    1: {
      padding: "4vw",
      top: "56%",
      left: "50%",
      width: "15%",
      fontSize: "1.4vw",
      borderRadius: "50%",
      background: `${defaultBGColor}`,
    },
  },
  50: {
    1: {
      top: "29.2%",
      left: "10.6%",
      width: "28%",
      fontSize: "1.4vw",
      deg: 98,
      borderBottom: `.3vw solid ${defaultColor}`,
    },
    2: {
      padding: "3vw",
      top: "60%",
      left: "23%",
      width: "12%",
      fontSize: "1.4vw",
      borderRadius: "50%",
      background: `${defaultBGColor}`,
    },
    3: {
      top: "46%",
      left: "21%",
      width: "48%",
      fontSize: "1.4vw",
      deg: 65.6,
      borderBottom: `.3vw solid ${defaultColor}`,
    },
    4: {
      top: "31.2%",
      left: "5.7%",
      width: "30%",
      fontSize: "1.4vw",
      deg: 99.3,
      borderBottom: `.3vw solid ${defaultColor}`,
    },
    5: {
      top: "35.5%",
      left: "0%",
      width: "34%",
      fontSize: "1.4vw",
      deg: 100,
      borderBottom: `.3vw solid ${defaultColor}`,
    },
    6: {
      top: "28.5%",
      left: "23%",
      width: "18.5%",
      fontSize: "1.4vw",
      deg: 94,
      borderBottom: `.3vw solid ${defaultColor}`,
    },
    7: {
      top: "28.6%",
      left: "14.6%",
      width: "27.5%",
      fontSize: "1.4vw",
      deg: 96,
      borderBottom: `.3vw solid ${defaultColor}`,
    },
  },
  кругл: {
    1: {
      paddingRight: "10%",
      top: "6%",
      left: "15%",
      width: "50%",
      fontSize: "1.4vw",
      deg: 3,
      borderBottom: `.3vw solid ${defaultColor}`,
    },
    2: {
      paddingRight: "27%",
      top: "31%",
      left: "18%",
      width: "60%",
      fontSize: "1.4vw",
      deg: -4,
      borderBottom: `.3vw solid ${defaultColor}`,
    },
    3: {
      top: "34%",
      left: "3%",
      width: "23%",
      fontSize: "1.4vw",
      deg: -110,
      borderBottom: `.3vw solid ${defaultColor}`,
    },
    4: {
      top: "25%",
      left: "13%",
      width: "20%",
      fontSize: "1.4vw",
      deg: -90,
      borderBottom: `.3vw solid ${defaultColor}`,
    },
    6: {
      top: "14%",
      left: "39%",
      width: "16%",
      fontSize: "1.4vw",
      deg: -80,
      borderBottom: `.3vw solid ${defaultColor}`,
    },
  },
  сереб: {
    1: {
      top: "60%",
      left: "0%",
      width: "15%",
      fontSize: "1.4vw",
      deg: 22,
      borderBottom: `.3vw solid ${defaultColor}`,
    },
    2: {
      top: "5.5%",
      left: "34%",
      width: "15%",
      fontSize: "1.4vw",
      deg: -11,
      borderBottom: `.3vw solid ${defaultColor}`,
    },
    3: {
      top: "42%",
      left: "49.3%",
      width: "25%",
      fontSize: "1.4vw",
      deg: -100,
      borderBottom: `.3vw solid ${defaultColor}`,
    },
    4: {
      top: "31%",
      left: "38.5%",
      width: "25%",
      fontSize: "1.4vw",
      deg: -103,
      borderBottom: `.3vw solid ${defaultColor}`,
    },
  },
  ГЭН: {
    1: {
      top: "0%",
      left: "25%",
      width: "73%",
      fontSize: "1.4vw",
      borderBottom: `.3vw solid ${defaultColor}`,
      deg: 180,
    },
  },
  шгво: {
    1: {
      top: "73%",
      left: "25%",
      width: "8%",
      fontSize: "2.5vw",
    },
  },
};
